---
title: "Data Exploration for Stable Isotopes"
author: "Caroline + Ariella"
date: '2023-1-25'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Want to learn:
- Percent C and N, and 15N/14N by:
  - Lake
  - Distance for plants
  - Elevation?
- For soils:
  - Percent N by percent OM

```{r}
# Load packages
library(tidyverse)
library(janitor)
library(lubridate)
library(car)

# Read in data
plant_iso_data <- read_csv("plant_iso_data.csv") %>% 
  janitor::clean_names()

```


# Graphs of percent C and percent N based on distance and fish
```{r}

# Make scatterplot of percent C as a function of distance and fish
plant_iso_data %>% 
  ggplot(aes(x = distance, y = pct_c, color = fish)) +
  geom_jitter() +
  ylim(48, 54) +
  geom_smooth(method="lm")  # fish presence decreases percent C, percent C decreases slightly over distance

res.lm <- lm(pct_c ~ distance + fish, data = plant_iso_data)
summary(res.lm) # fish presence significantly decreases percent C in plants

# Make scatterplot of percent N as a function of distance and fish  
plant_iso_data %>% 
  ggplot(aes(x = distance, y = pct_n, color = fish)) +
  geom_jitter() +
  geom_smooth(method="lm") # fish presence increases percent N, percent N increases with distance

res.lm2 <- lm(pct_n ~ distance * fish, data = plant_iso_data)
summary(res.lm2) # fish presence and distance (but not interaction) significantly increase percent N, distance more than fish presence


```
